# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 438c7af2cca4502cbdc3470182bfac5f186281bea0f5badbac515f206e541ecb01dce815a21be2cce85b7bb1f7e00b4be8b1f21363630869d06869ad9ea1707b

test:
  secret_key_base: dfb37cc0bf4bbdfe8e5dacc16ca2be4fddb7f5be37fcffc091d296eb5ca8f7d85e7e305b02136cd570469b7016d52bee3a7e438e15c0e3d686f79639269716a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
